import Head from "next/head";
import LegalLayout from "../components/LegalLayout";

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of Service — DecisionOS</title>
        <meta name="robots" content="noindex" />
      </Head>
      <LegalLayout title="Terms of Service" lastUpdated="July 2, 2026">
        <p>
          These Terms of Service ("Terms") govern your use of decisionpilot.tech, operated by{" "}
          Nicolae-Abel Bolos-Ardeleanu ("DecisionOS", "we", "us"). By using the Service,
          you agree to these Terms.
        </p>

        <h2>1. What DecisionOS is</h2>
        <p>
          DecisionOS is an AI-assisted decision-support tool. You describe the situation, your goal, your constraints, and the
          alternatives you're weighing; the AI analyzes them and produces a recommendation with plain-language reasoning, risks,
          and an action plan. You record what you actually decided and, later, what happened — the AI never makes the decision
          for you, and every recommendation is something you choose to accept, adapt, or reject.
        </p>

        <h2>2. Not professional advice</h2>
        <p>
          Recommendations, analysis, and action plans generated by DecisionOS — including AI chat responses — are for general
          informational purposes only. They are not financial, legal, medical, or other professional advice, and should not be
          treated as a guarantee of any outcome. Always verify important details independently, and consult a qualified
          professional before acting on a high-stakes decision.
        </p>

        <h2>3. Plans and billing</h2>
        <ul>
          <li><strong>Free</strong> — unlimited Decision Objects, the full Decision Wizard, AI-generated recommendations, and Outcome/Reflection recording, with access to your 10 most recent Decisions in your Decision History. No signup is required to start or complete a Decision.</li>
          <li><strong>Pro (€4.99/month)</strong> — everything in Free, plus unlimited Decision History, the AI Chat feature, Action Plan editing, and priority AI response times.</li>
          <li><strong>Premium (€9.99/month)</strong> — everything in Pro, plus deeper AI analysis, Lessons Learned surfaced from your past decisions, and premium support.</li>
          <li>No step of the Decision process is ever locked behind a paid plan — plans add depth and history, not access to making a decision.</li>
          <li>Paid plans are billed monthly via Stripe. You can cancel at any time; access continues until the end of the current billing period, after which your account reverts to Free with no data loss.</li>
          <li>Unless required by law, payments already made are non-refundable for partial billing periods.</li>
          <li>We may change pricing with reasonable advance notice to active subscribers.</li>
        </ul>

        <h2>4. Affiliate disclosure</h2>
        <p>
          DecisionOS participates in affiliate programs, including Amazon Associates, CJ Affiliate, and Awin. Where your own
          Final Decision maps to a specific purchasable product or service, we may show a link to that option, and may earn a
          commission if you complete a purchase through it, at no extra cost to you. This link is only ever to the option you
          chose — never a sponsored alternative — and affiliate relationships never influence what the AI recommends.
        </p>

        <h2>5. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for any unlawful purpose</li>
          <li>Attempt to disrupt, overload, or reverse-engineer the Service</li>
          <li>Use automated tools to scrape the Service or circumvent plan limits</li>
          <li>Submit harmful, abusive, or illegal content via the AI Chat feature</li>
        </ul>

        <h2>6. Intellectual property</h2>
        <p>
          All content, branding, and design on DecisionOS belong to Nicolae-Abel Bolos-Ardeleanu unless otherwise credited. You
          may not copy, resell, or redistribute the Service without permission.
        </p>

        <h2>7. Disclaimer and limitation of liability</h2>
        <p>
          The Service is provided "as is" without warranties of any kind. To the maximum extent permitted by law, we are not
          liable for any indirect, incidental, or consequential damages arising from your use of the Service, including
          decisions made based on AI-generated recommendations.
        </p>

        <h2>8. Termination</h2>
        <p>
          We may suspend or terminate access to the Service for users who violate these Terms. You may stop using the Service
          and cancel your subscription at any time.
        </p>

        <h2>9. Governing law</h2>
        <p>
          These Terms are governed by the laws of Germany, without
          regard to conflict of law principles.
        </p>

        <h2>10. Changes to these Terms</h2>
        <p>We may update these Terms occasionally. Continued use of the Service after changes means you accept the updated Terms.</p>

        <h2>11. Contact</h2>
        <p>
          Questions about these Terms? Reach us at contact@decisionpilot.tech or via our{" "}
          <a href="/contact" style={{ color: "#1A56DB" }}>Contact page</a>.
        </p>
      </LegalLayout>
    </>
  );
}
