import Head from "next/head";
import LegalLayout from "../components/LegalLayout";

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of Service — DecisionPilot</title>
        <meta name="robots" content="noindex" />
      </Head>
      <LegalLayout title="Terms of Service" lastUpdated="June 21, 2026">
        <p>
          These Terms of Service ("Terms") govern your use of decisionpilot.tech, operated by{" "}
          Nicolae-Abel Bolos-Ardeleanu ("DecisionPilot", "we", "us"). By using the Service,
          you agree to these Terms.
        </p>

        <h2>1. What DecisionPilot is</h2>
        <p>
          DecisionPilot is an AI-assisted comparison and recommendation tool. We help you compare options across categories like
          vacations, cars, electronics, and more, and suggest picks based on your answers. We are an independent comparison
          service — we are not affiliated with the brands, retailers, or partners we feature unless explicitly stated.
        </p>

        <h2>2. Not professional advice</h2>
        <p>
          Recommendations generated by DecisionPilot — including AI chat responses — are for general informational purposes
          only. They are not financial, legal, medical, or other professional advice, and should not be treated as a guarantee
          of price, availability, or suitability. Always verify details directly with the provider before making a purchase or
          booking.
        </p>

        <h2>3. Plans and billing</h2>
        <ul>
          <li><strong>Free</strong> — limited daily decisions and AI chat messages, no signup required.</li>
          <li><strong>Pro ($4.99/month)</strong> and <strong>Premium ($9.99/month)</strong> — paid subscriptions with extended limits and features, billed monthly via Stripe.</li>
          <li>You can cancel a paid subscription at any time; access continues until the end of the current billing period.</li>
          <li>Unless required by law, payments already made are non-refundable for partial billing periods.</li>
          <li>We may change pricing with reasonable advance notice to active subscribers.</li>
        </ul>

        <h2>4. Affiliate disclosure</h2>
        <p>
          DecisionPilot participates in affiliate programs with partners such as AutoScout24, CHECK24, Booking.com, Wayfair,
          Sixt, and Europcar. We may earn a commission when you click through and complete a purchase or booking, at no extra
          cost to you. Commission never influences which option we rank or recommend as best for you — our comparisons aim to
          stay independent.
        </p>

        <h2>5. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for any unlawful purpose</li>
          <li>Attempt to disrupt, overload, or reverse-engineer the Service</li>
          <li>Use automated tools to scrape or abuse the Free plan's limits</li>
          <li>Submit harmful, abusive, or illegal content via the AI chat feature</li>
        </ul>

        <h2>6. Intellectual property</h2>
        <p>
          All content, branding, and design on DecisionPilot — including the Asel character — belong to{" "}
          Nicolae-Abel Bolos-Ardeleanu unless otherwise credited. You may not copy, resell, or
          redistribute the Service without permission.
        </p>

        <h2>7. Disclaimer and limitation of liability</h2>
        <p>
          The Service is provided "as is" without warranties of any kind. To the maximum extent permitted by law, we are not
          liable for any indirect, incidental, or consequential damages arising from your use of the Service, including
          decisions made based on AI-generated recommendations.
        </p>

        <h2>8. Termination</h2>
        <p>
          We may suspend or terminate access to the Service for users who violate these Terms. You may stop using the Service
          and cancel your subscription at any time.
        </p>

        <h2>9. Governing law</h2>
        <p>
          These Terms are governed by the laws of Germany, without
          regard to conflict of law principles.
        </p>

        <h2>10. Changes to these Terms</h2>
        <p>We may update these Terms occasionally. Continued use of the Service after changes means you accept the updated Terms.</p>

        <h2>11. Contact</h2>
        <p>
          Questions about these Terms? Reach us at contact@decisionpilot.tech or via our{" "}
          <a href="/contact" style={{ color: "#1A56DB" }}>Contact page</a>.
        </p>
      </LegalLayout>
    </>
  );
}
